// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFpwi3k7Qth9MiqqRGKstY0Zkj_vrcdFY',
    appId: '1:193864081571:web:1428a1497e2bdb2ae61f16',
    messagingSenderId: '193864081571',
    projectId: 'edutrack-admin',
    authDomain: 'edutrack-admin.firebaseapp.com',
    storageBucket: 'edutrack-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dI8nKu8-3_BVA-M47d5nL3wp5VQndlM',
    appId: '1:193864081571:android:8ba4302811ebe276e61f16',
    messagingSenderId: '193864081571',
    projectId: 'edutrack-admin',
    storageBucket: 'edutrack-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wo2sM_rd0mLqBetkJoNamILPi6DE4_w',
    appId: '1:193864081571:ios:c7ec37a7c6b88425e61f16',
    messagingSenderId: '193864081571',
    projectId: 'edutrack-admin',
    storageBucket: 'edutrack-admin.firebasestorage.app',
    iosClientId: '193864081571-caeqrrv9emifj994vb7jmvi1sun6ho58.apps.googleusercontent.com',
    iosBundleId: 'com.example.omrAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wo2sM_rd0mLqBetkJoNamILPi6DE4_w',
    appId: '1:193864081571:ios:c7ec37a7c6b88425e61f16',
    messagingSenderId: '193864081571',
    projectId: 'edutrack-admin',
    storageBucket: 'edutrack-admin.firebasestorage.app',
    iosClientId: '193864081571-caeqrrv9emifj994vb7jmvi1sun6ho58.apps.googleusercontent.com',
    iosBundleId: 'com.example.omrAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5T_Ohk9oISm63UMZSGplRCyivsevKzQ',
    appId: '1:193864081571:web:e6a79f35679a1ef5e61f16',
    messagingSenderId: '193864081571',
    projectId: 'edutrack-admin',
    authDomain: 'edutrack-admin.firebaseapp.com',
    storageBucket: 'edutrack-admin.firebasestorage.app',
  );
}
